# Generated by Django 6.0.5 on 2026-05-22 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del equipo')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Nombre del contacto')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Teléfono del contacto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('dni', models.CharField(max_length=20, verbose_name='DNI')),
                ('is_active', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('injury_replacement', models.BooleanField(default=False, verbose_name='Reemplazo por lesión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournaments.team', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('teams', models.ManyToManyField(related_name='groups', to='tournaments.team', verbose_name='Equipos')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('format', models.CharField(choices=[('round_robin', 'Round Robin'), ('groups_elimination', 'Grupos + Eliminación')], max_length=30, verbose_name='Formato')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género')),
                ('category', models.CharField(choices=[('libre', 'Libre'), ('veteranos', 'Veteranos')], default='libre', max_length=20, verbose_name='Categoría')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('open', 'Inscripción abierta'), ('in_progress', 'En curso'), ('finished', 'Finalizado')], default='draft', max_length=20, verbose_name='Estado')),
                ('min_players', models.PositiveIntegerField(default=5, verbose_name='Mínimo de jugadores')),
                ('max_players', models.PositiveIntegerField(default=15, verbose_name='Máximo de jugadores')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='resources.resource', verbose_name='Cancha')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.sport', verbose_name='Deporte')),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournament', verbose_name='Torneo'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('group', 'Fase de grupos'), ('round_of_16', 'Octavos'), ('quarterfinal', 'Cuartos de final'), ('semifinal', 'Semifinal'), ('third_place', 'Tercer puesto'), ('final', 'Final')], default='group', max_length=20, verbose_name='Fase')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('home_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Goles local')),
                ('away_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Goles visitante')),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('in_progress', 'En curso'), ('finished', 'Finalizado'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournaments.group', verbose_name='Grupo')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='resources.resource', verbose_name='Cancha')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='tournaments.team', verbose_name='Equipo visitante')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='tournaments.team', verbose_name='Equipo local')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournaments.tournament', verbose_name='Torneo'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('tournament', 'name')},
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.PositiveIntegerField(default=0, verbose_name='PJ')),
                ('won', models.PositiveIntegerField(default=0, verbose_name='PG')),
                ('drawn', models.PositiveIntegerField(default=0, verbose_name='PE')),
                ('lost', models.PositiveIntegerField(default=0, verbose_name='PP')),
                ('goals_for', models.PositiveIntegerField(default=0, verbose_name='GF')),
                ('goals_against', models.PositiveIntegerField(default=0, verbose_name='GC')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standings', to='tournaments.group', verbose_name='Grupo')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournaments.team', verbose_name='Equipo')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournaments.tournament', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
                'ordering': ['-won', '-goals_for'],
                'unique_together': {('tournament', 'group', 'team')},
            },
        ),
    ]
