# Generated by Django 6.0.5 on 2026-05-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birth_date',
            field=models.DateField(default='1990-01-01', verbose_name='Fecha de nacimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='veteran_min_age',
            field=models.PositiveIntegerField(default=38, verbose_name='Edad mínima veteranos'),
        ),
    ]
