# Generated by Django 6.0.5 on 2026-05-24 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_player_birth_date_tournament_veteran_min_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='yellow_cards_suspension',
            field=models.PositiveIntegerField(default=3, verbose_name='Amarillas para suspensión'),
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('goal', 'Gol'), ('yellow', 'Tarjeta amarilla'), ('red', 'Tarjeta roja')], max_length=10, verbose_name='Tipo de evento')),
                ('minute', models.PositiveIntegerField(blank=True, null=True, verbose_name='Minuto')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tournaments.match', verbose_name='Partido')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tournaments.player', verbose_name='Jugador')),
            ],
            options={
                'verbose_name': 'Evento de partido',
                'verbose_name_plural': 'Eventos de partido',
                'ordering': ['minute'],
            },
        ),
    ]
