# Generated by Django 6.0.5 on 2026-05-25 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_yellow_cards_suspension_matchevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='champion_tournaments', to='tournaments.team', verbose_name='Campeón'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='runner_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runner_up_tournaments', to='tournaments.team', verbose_name='Subcampeón'),
        ),
    ]
