# Generated by Django 6.0.5 on 2026-05-19 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('is_closed', models.BooleanField(default=True, verbose_name='Cerrado todo el día')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Hora de apertura especial')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Hora de cierre especial')),
                ('reason', models.CharField(max_length=200, verbose_name='Motivo')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to='resources.resource', verbose_name='Recurso')),
            ],
            options={
                'verbose_name': 'Excepción de disponibilidad',
                'verbose_name_plural': 'Excepciones de disponibilidad',
                'ordering': ['date'],
                'unique_together': {('resource', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('open_time', models.TimeField(verbose_name='Hora de apertura')),
                ('close_time', models.TimeField(verbose_name='Hora de cierre')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='resources.resource', verbose_name='Recurso')),
            ],
            options={
                'verbose_name': 'Regla de disponibilidad',
                'verbose_name_plural': 'Reglas de disponibilidad',
                'ordering': ['resource', 'day_of_week'],
                'unique_together': {('resource', 'day_of_week')},
            },
        ),
    ]
