# Generated by Django 6.0.5 on 2026-05-19 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='Ícono')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Deporte',
                'verbose_name_plural': 'Deportes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidad (jugadores)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio por hora')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='resources/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='resources.sport', verbose_name='Deporte')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['sport', 'name'],
            },
        ),
    ]
